### ISSUE TITLE
Could not access the zendo url

### ISSUE THREAD

**Issue by JamesCao2048** [NougatCA/CrossCodeBench#1]
Dear CrossCodeBench,
Thank you too much for the interesting work! However, the zendo url https://zenodo.org/record/7321934 seems could not be accessed now.

See the screenshot below.
<img width="1469" alt="截屏2023-11-14 10 49 23" 
src="https://github.com/NougatCA/CrossCodeBench/assets/25586216/bad55cab-6b61-4b1c-a833-bfa91314fb76">

Looking forward to your reply. Thanks!

**Comment by NougatCA** [comment]
Hi, @JamesCao2048 

It looks like your you are having some problems with your network, since the URL works fine here.
<img width="1468" alt="image" src="https://github.com/NougatCA/CrossCodeBench/assets/28826655/36c22b3b-3eb2-4e04-aab4-afa9e18fead3">

Thanks for your interest in our work. Hope you can address your network issue as soon as possible.

**Comment by JamesCao2048** [comment]
Thanks for your kind reply, it is the network error and I fixed it.
